# Site settings
author: Khoi Nguyen
title: The Art of Code
header-img: img/home-bg.png
email: khoinguyenkc@gmail.com
copyright_name: Khoi Nguyen
description: > # this means to ignore newlines until "baseurl:"
  Musings on Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  khoinguyenkc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
